### ISSUE TITLE
Headshot seemingly random dice roll instead of actual head hitbox

### ISSUE THREAD

**Issue by Kaleidio** [chronosacaria/Headshot-Forge#4] opened 2022-05-08 18:29 UTC
I haven't taken a check on the code, but even on a simple zombie if I hit it's feet there's a quite easy to calculate chance it counts as a headshot when it clearly wasn't.  Is your mod not doing actual hitbox detection?

I really do wish to add this mod to my pack but as it stands it isn't working properly on any entity.

**Comment by chronosacaria** [comment] 2022-05-08 19:09
Do you have other mods installed? It should be working properly

**Comment by Colin-J-Wood** [comment] 2022-05-09 10:56
Yeah, it's a 300+ mod pack.  I'm not sure I'd be able to really sort through it easily.  You can test it yourself by dropping your mod in here:

https://www.curseforge.com/minecraft/modpacks/kaleidios-battle-pack

testing is being done specifically on the 5.0.0 beta since it has new guns.

This is my alt by the way

**Comment by Colin-J-Wood** [comment] 2022-05-09 10:57
I believe it's possible some mod is somehow making projectiles return the landing place they should renderlayer an arrow to, and not where the projectile actually landed.  but that might be a red herring, and I have yet to do further testing on my dev branch which has had quite a few mods stripped out for performance reasons (and more to come)

**Comment by Colin-J-Wood** [comment] 2022-05-09 11:42
Okay as it turns out it truly is down to an issue with my gun projectiles landing on the entity, it seems the hitbox is way too large.

**Comment by chronosacaria** [comment] 2022-06-13 14:29
Since it turns out that this was not an issue caused by Headshot, this issue shall be closed

**Closed by chronosacaria** 2022-06-13 14:29 UTC

**Comment by Kaleidio** [comment] 2022-06-13 19:54
I'm still having difficulty figuring out a way to patch it on my end in my gun mod's codebase.  is there any way I can ask for your assistance?

**Comment by Kaleidio** [comment] 2022-06-21 08:23
I've opened a new issue as I found the issue is due to something quite specific to mojang code interacting with headshot mod.
